# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CircleCue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for CircleCue
  
  pod 'GoogleMaps', '7.1.0'
  pod 'NVActivityIndicatorView'
  pod 'VIMediaCache'
  pod 'Firebase/Messaging'
  pod 'FirebaseAnalytics'
  pod 'SDWebImagePDFCoder'
  pod 'lottie-ios'
  pod 'ZegoUIKitPrebuiltLiveStreaming'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
  # fix for xcode14 codesign for dependencies - remove after fix oficially
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
